### ISSUE TITLE
Conda envs don't apply to commands shelling out in jupyter python notebook

### ISSUE THREAD

**Issue by kclem** [SD2E/jupyteruser-sd2e#17] opened 2018-05-19 04:18 UTC
I can create a custom conda environment, and can see it in the dropdown under 'new'. When I create a new jupyter python notebook with the custom environment, I can import the applicable modules, but when I shell out a command, it is running in the base conda environment instead of the one I selected.

## Expected Behaviour
When I click new->{custom conda environment} it pulls up a new ipython notebook if I type:
!conda envs list
it should see that I am in my custom environment and allow me to run commands using programs I have installed in that custom environment.

## Current Behaviour
`!conda envs list`
```
# conda environments:
#
sims                     /home/jupyter/tacc-work/jupyter_packages/envs/sims
base                  *  /opt/conda
python2                  /opt/conda/envs/python2
```
In addition, I can't switch to the custom environment because `/bin/sh: 1: source: not found`

## Steps to Reproduce (for bugs)
https://jupyter.sd2e.org/user/kenclem1/notebooks/tacc-work/maverick/SafeGenes/SimulationsDemo/envTest.ipynb
1. Create custom conda environment using details at:  /examples/Advanced Jupyter.ipynb on jupyter.sd2e.org. Install for example the program pindel using the command `conda install -c bioconda pindel`
2. Create a new notebook using that conda environment using the new->{custom environment}
3. Type `!conda envs`
4. Observe that the conda environment has not been loaded.
5. Attempt to run pindel using the command `pindel` and note again that the conda environment has not been loaded.

## Context
I need to create a conda environment that includes python packages as well as software packages called within my ipython notebook and the python scripts.

**Comment by zyndagj** [comment] 2018-05-19 14:46
Even though the new kernels don't `activate` the new conda environments, they do work correctly for everything python.

### Look for a python package that doesn't exist.

![screen shot 2018-05-19 at 9 20 27 am](https://user-images.githubusercontent.com/6790115/40269656-26eeb198-5b47-11e8-802c-fb752ea3f25b.png)

### Create new environment with package, and create jupyter kernel

![screen shot 2018-05-19 at 9 23 56 am](https://user-images.githubusercontent.com/6790115/40269664-621939f0-5b47-11e8-9926-5d0f3e04f755.png)

### Choose new kernel

![screen shot 2018-05-19 at 9 24 10 am](https://user-images.githubusercontent.com/6790115/40269670-6c8d6438-5b47-11e8-8630-583393b7f8af.png)

### Explore environment

![screen shot 2018-05-19 at 9 25 37 am](https://user-images.githubusercontent.com/6790115/40269675-7fbc990c-5b47-11e8-86a9-7e00ea8299f4.png)

You'll notice that even though listing environments on a subshell says we're on `base`
- `pysam` correctly loads
- Jupyter correctly uses `/home/jupyter/tacc-work/jupyter_packages/envs/pysam/bin/python`

This is because Jupyter was designed to interact with python environments, not conda environments. Conda is just a specific distribution of python. To fix `pip install --user` in our default Python 2 and Python 3 kernels, I manually modify their spec to load their respective environments.

https://github.com/SD2E/jupyteruser-sd2e/blob/master/images/base/Dockerfile#L211

I have not automated this process because it breaks non-python and non-conda kernels. If your `sims` environment is based on python, you can modify your

```
/home/jupyter/tacc-work/jupyter_packages/share/jupyter/kernels/sims/kernel.json
```

to function like

```
cat /opt/conda/share/jupyter/kernels/python3/kernel.json

{
  "argv": [
    "activate_kernel",
    "base",
    "{connection_file}"
  ],
  "display_name": "Python 3",
  "language": "python"
}
```

**Comment by kclem** [comment] 2018-05-29 18:10
In some workflows, you also need to call specific versions of programs that you have installed as part of the conda environment, such as samtools, bowtie, or pindel. If we can only install one version on either the python2 or python3 version, our workflow will not be reproducible because those tools have other dependencies in the environment. A solution that we have is to first switch to the correct conda environment and then to launch jupyter from within that environment. Would it be possible to implement this?

**Comment by lucapinello** [comment] 2018-05-30 16:48
@zyndagj thanks for the quick reply. Those notebooks are a way to show reproducible workflow step by step. This is one of the goals we have for the data sharing effort with DARPA. I would appreciate if you could provide a solution.

**Comment by zyndagj** [comment] 2018-06-01 20:53
https://github.com/SD2E/jupyteruser-sd2e/blob/master/images/base/examples/Loading_Conda_Environments_in_Kernels.ipynb

Should resolve your issue, and will be included in the next release of the server.

**Closed** 2018-10-31 15:48 UTC
